application:
  subdomain: borui
  background_task: true
  public_path:
    - /

  upstreams:
    - location: /
      backend: http://host.lzcapp:3002/

services:
  borui:
    # ghcr.io/dockers-x/borui:0.2.7
    image: registry.lazycat.cloud/czyt/dockers-x/borui:c076536133254473
    binds:
      - /lzcapp/var/data:/app/data
    environment:
      - DATABASE_URL=sqlite:///app/data/borui.db
      - BIND_ADDR=0.0.0.0:3002
      - RUST_LOG=info,borui=debug
      - JWT_SECRET={{ stable_secret "bore#jwt" }}
      - INIT_ADMIN={{ .U.init_admin }}
      - INIT_ADMIN_PASSWORD={{ .U.init_admin_password }}
    network_mode: host
